print('-------------------------')
print('|     JOGO DO GALO      |')
print('-------------------------')
print()
print('         |     |     ')
print('----------------')
print('    |     |     ')
print('----------------')
print('    |     |     ')
